@startuml MyMLApplicationDiagram

class App {
    - selected_tab: String
    - uploaded_file: File
    - data: DataTable
    + run()
    + load_data()
    + visualize_data()
    + perform_ml()
    + show_info()
}

class DataLoader {
    - data: DataTable
    + load_data(file: File): DataFrame
}

class Visualization {
    - data: DataTable
    + PCA_plot()
    + UMAP_plot()  ' Replaced LDA with UMAP
    + EDA_histogram()
    + EDA_scatter_plot()
}

class PCAPlot {
    - data: DataTable
    + visualize_plot()
}

class UMAPPlot {
    - data: DataTable
    + visualize_plot()
}

class EDAHistogram {
    - data: DataTable
    + visualize_plot()
}

class EDAScatterPlot {
    - data: DataTable
    + visualize_plot()
}

Visualization --> PCAPlot : uses
Visualization --> UMAPPlot : uses
Visualization --> EDAHistogram : uses
Visualization --> EDAScatterPlot : uses

class MachineLearning {
    - data: DataTable
    + Classification
    + FeatureSelection
}

class Classification {
    - data: DataTable
    + KNearestNeighbors
    + SupportVectorMachine
}

class KNearestNeighbors {
    - data: DataTable
    + classify(data: DataFrame, features: List)
}

class SupportVectorMachine {
    - data: DataTable
    + classify(data: DataFrame, features: List)
}

class FeatureSelection {
    - data: DataTable
    + feature_selection(X: DataFrame, y: Series, k: int): (DataFrame, List[int])
}

' Define relationships
App --> DataLoader : uses
App --> Visualization : uses
App --> MachineLearning : uses
MachineLearning --> FeatureSelection : uses

@enduml
